default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: tjay
  password: nemuqa89
  host: localhost

development:
  <<: *default
  database: hello_rails_backend_development

test:
  <<: *default
  database: hello_rails_backend_test

production:
  <<: *default
  database: hello_rails_backend_production
